### ISSUE TITLE
[BUG] Website download link not working (404)

### ISSUE THREAD

**Issue by vicenterusso** [laradumps/laradumps#103]
### What happened?

Download link not working (404)

https://laradumps.dev/get-started/get-started/installation?id=desktop-app

**Comment by dansysanalyst** [comment]
Hi @vicenterusso, where is this link published? (where can I find it?)

At the time of writing this reply, the correct link is: 
https://laradumps.dev/get-started/installation.html#desktop-app

**Comment by vicenterusso** [comment]
Heres a screenshot

![](https://i.imgur.com/xS3JuJw.png)

**Comment by luanfreitasdev** [comment]
Hi @vicenterusso , thank you for viewing this. I fixed the broken links
