### ISSUE TITLE
[BUG] Permission denied

### ISSUE THREAD

**Issue by scajal** [laradumps/laradumps#104]
# 🛻 LaraDumps Bug Report

<table><tr><td>❗ You <b>MUST</b> use this template to submit an issue or it will be CLOSED. ❗</td></tr></table><br/>

Thank you for reporting a bug and helping us to improve our software!

## Guidelines

`   🐛 `   We use GitHub Issues **EXCLUSIVELY** for tracking bugs and unexpected software behavior.

`   🙏 `  Questions like _"How to...",_ "_how can I..."_, _"I would like to..."_ should be posted in the LaraDumps [Discussions](https://github.com/laradumps/laradumps/discussions) tab.

`   ✍️ `  Give this report a short but meaningful title. Make it easy to spot for others who might be facing the same issue.

`   ⚠️ `  Issues that do not describe a bug will be closed.

#### Have you searched through other issues to see if your problem is already reported or has been fixed?

- [X ] Yes - I did not find it.
- [ ] No

#### Did you read the [documentation](https://laradumps.dev/)?

- [ X] Yes - I did not find it.
- [ ] No

#### Have you tried to reconfigure LaraDumps?

To configure LaraDumps, run: `php artisan ds:init`.

- [ ] Yes - I didn't work.
- [ X] No, I believe this error is not related the configuration.

### Software Version

You can run `composer show -i` and `npm list` to list installed package with their versions.

| Software  | Version (exactly) |
|-----------|-------------------|
| LaraDumps App | 1.7.2                  |
| LaraDumps package   | 1.11.1                   |
| Laravel  | 10.9.0                   | 
| Operating System  | Windows 11 x64                  |

#### What is your project Environment?

- [ ] Laravel Valet
- [ ] Laravel Sail
- [ ] Docker
- [ ] XAMPP
- [ ] Laragon
- [X ] Other - please specify: PHP CLI

---

### What happened?

I'm having an error whenever I try to do any action related to laradumps, in a Laravel project:
```bash
In LaraDumpsServiceProvider.php line 52:

require_once(<path to my project>\vendor\laradumps\laradumps\src./functions.php): Failed to open stream: Permission denied
```

### Steps to Reproduce the problem

Install the package in a Laravel app.

## Extra information

**Screenshots**

**Comment by scajal** [comment]
Related to PR [#105 ](https://github.com/laradumps/laradumps/pull/105)

**Comment by luanfreitasdev** [comment]
Fixed https://github.com/laradumps/laradumps/releases/tag/v1.11.2
