### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Joso997** [laradumps/laradumps#110]
# 🛻 LaraDumps Bug Report

<table><tr><td>❗ You <b>MUST</b> use this template to submit an issue or it will be CLOSED. ❗</td></tr></table><br/>

Thank you for reporting a bug and helping us to improve our software!

## Guidelines

`   🐛 `   We use GitHub Issues **EXCLUSIVELY** for tracking bugs and unexpected software behavior.

`   🙏 `  Questions like _"How to...",_ "_how can I..."_, _"I would like to..."_ should be posted in the LaraDumps [Discussions](https://github.com/laradumps/laradumps/discussions) tab.

`   ✍️ `  Give this report a short but meaningful title. Make it easy to spot for others who might be facing the same issue.

`   ⚠️ `  Issues that do not describe a bug will be closed.

#### Have you searched through other issues to see if your problem is already reported or has been fixed?

- [x ] Yes - I did not find it.
- [ ] No

#### Did you read the [documentation](https://laradumps.dev/)?

- [x ] Yes - I did not find it.
- [ ] No

#### Have you tried to reconfigure LaraDumps?

To configure LaraDumps, run: `php artisan ds:init`.

- [x ] Yes - I didn't work.
- [ ] No, I believe this error is not related the configuration.

### Software Version

You can run `composer show -i` and `npm list` to list installed package with their versions.

| Software  | Version (exactly) |
|-----------|-------------------|
| LaraDumps App |                1.7.2   |
| LaraDumps package   |               newest    |
| Laravel  |             v9.40.1      |
| Operating System  |     windows 10              |

#### What is your project Environment?

- [ ] Laravel Valet
- [ ] Laravel Sail
- [ ] Docker
- [ ] XAMPP
- [ ] Laragon
- [ x] Other - please specify: ________Laravel Homestead

---

### What happened?

I tried multiple addresses in .env but I never received anything when using ds(); on 'welcome' route as in an example. I am using simple Laravel Homestead implementation.

### Steps to Reproduce the problem

First click on "FOO" then....

### Suggestions

(Do you have any idea how we can fix it?)

## Extra information

**Screenshots**

**Comment by dansysanalyst** [comment]
Hi @Joso997,

I am a macOS user and sadly, I could not get Laravel Homestead on my old Windows computer.

Did you try using the IP `10.0.2.2` (Homestead + VirtualBox)? 

Also, connecting to your machine via SSH using `homestead ssh` and then execute `route` can provide some insights.
