### ISSUE TITLE
Melhorar a visualização de json

### ISSUE THREAD

**Issue by niodio** [laradumps/laradumps#114]
Fala Luan, procurei na documentação mas não encontrei nada parecido, tem hora que temos que usar mais de 1 endpoint de uma API utilizando o JSON do endpoint anterior, ao dar um dd no POSTMAN eu consigo pegar o JSON em string e jogar ele para o próximo endpoint, tentei a mesma coisa com o LARADUMPS mas a string se perde de vista ficando em uma só linha, tem algum comando para dar uma especie de beautfy no json para melhor leitura?

OBS, ds($json)->isJson() não serve pois este mostra o json como objeto.

OBS2, muito top o Laradumps, parabéns...

**Comment by luanfreitasdev** [comment]
Olá @niodio . Pode delar mais contexto com capturas de telas ?

**Comment by niodio** [comment]
O update para a versão 2.0.2 deu errado e quando tentei voltar para a versão anterior simplesmente não funcionou, semana que vem eu tento novamente

**Comment by niodio** [comment]
Bom dia Luan, segue o print do json que montei para tentar enviar para API, nesse caso eu monto 3 jsons diferente e queria printar os 3 no laradumps mas ele printa como stringue perdendo o restante do json de vista.

![image](https://github.com/laradumps/laradumps/assets/16155015/61df2b36-b1f0-4a50-8372-087d04e5002c)

**Comment by luanfreitasdev** [comment]
Como isso esta funcionando na versao mais recente, estou fechando.

![image](https://github.com/laradumps/laradumps/assets/33601626/55478888-b01d-43f7-a3cf-43484e54f2fb)

Obrigado!
