### ISSUE TITLE
Não está debugando componente Livewire na versão 2.0.2

### ISSUE THREAD

**Issue by Henriquex25** [laradumps/laradumps#115]
Depois que fiz a atualização pra nova versão, não estou mais conseguindo fazer o debug dos componentes Livewire. Procurei nas Releases Notes se foi removido essa opção e não encontrei nada sobre o assunto

**Comment by luanfreitasdev** [comment]
Olá @Henriquex25 . O debug do livewire por enquanto foi removido. Isso por causa de versão 3 que está para ser lançada, pode ter algumas diferenças de comportamento
