### ISSUE TITLE
[BUG] Erro ao rodar o configure

### ISSUE THREAD

**Issue by niodio** [laradumps/laradumps#116]
Erro na atualização do laradumps quando tento rodar o configure parece que não esta identificando o APP como aberto e não prossegue a configuração

![image](https://github.com/laradumps/laradumps/assets/16155015/48ec7e22-c921-491e-b45b-ad695f7f516b)

**Comment by luanfreitasdev** [comment]
@niodio . Como esta a chave DS_APP_HOST ? Vi que você esta usando Sail

**Comment by Jeferson-N** [comment]
Boa noite!

estou com o mesmo problema apontado acima.

![image](https://github.com/laradumps/laradumps/assets/18485370/e167bd48-03d2-4568-8cbf-f95319ce1b9e)


configuração do DS_APP_HOST
![image](https://github.com/laradumps/laradumps/assets/18485370/b1689491-22ff-4710-b292-b6697c70e7e9)

**Comment by Jeferson-N** [comment]
Bom dia!

Estou utilizando o sail em um ambiente WSL2, porém não funcionou com a configuração abaixo.

![image](https://github.com/laradumps/laradumps/assets/18485370/e0d71a75-f0bc-49c9-9207-bfbe27c56add)

![image](https://github.com/laradumps/laradumps/assets/18485370/5b6859e4-0556-4ba0-a259-cc6cacf2086b)


Existe alguma outra configuração ?

**Comment by ana-lisboa** [comment]
Igual, estou um bocado perdida com o que fazer com o resultado de correr esse comando `pwd` . 
Será uma questão de apenas melhorar essa indicação de onde colar esse valor?

ao usar o ip, como indica este comentario, resolvi o problema https://github.com/laradumps/laradumps/issues/86#issuecomment-1430381820

**Comment by luanfreitasdev** [comment]
Closed, see https://github.com/laradumps/laradumps/issues/121#issuecomment-1965468070
