### ISSUE TITLE
[BUG] Mailable dump with raw data fails

### ISSUE THREAD

**Issue by Krato** [laradumps/laradumps#117]
# 🛻 LaraDumps Bug Report

#### Have you searched through other issues to see if your problem is already reported or has been fixed?

- [ X] Yes - I did not find it.
- [ ] No

#### Did you read the [documentation](https://laradumps.dev/)?

- [X ] Yes - I did not find it.
- [ ] No

#### Have you tried to reconfigure LaraDumps?

To configure LaraDumps, run: `vendor/bin/laradumps configure`.

- [ X] Yes - I didn't work.
- [ ] No, I believe this error is not related the configuration.

### Software Version

You can run `composer show -i` and `npm list` to list installed package with their versions.

| Software  | Version (exactly) |
|-----------|-------------------|
| LaraDumps App | v2.1.0|
| LaraDumps package   |v2.1.0|
| LaraDumps core   |v0.2.0|
| Laravel  |9.52.10|
| Operating System  |MAC|

#### What is your project Environment?

- [X ] Laravel Valet
- [ ] Laravel Sail
- [ ] Docker
- [ ] XAMPP
- [ ] Laragon
- [ ] Other - please specify: ________

---

### What happened?

When sending and email with Raw data throws an error on laradump:

```
ERROR  Call to a member function getPath() on string in vendor/laradumps/laradumps/src/Payloads/MailPayload.php on line 36.
````

### Steps to Reproduce the problem

Create a Mailable and add an attachment using `fromData`. For example:

```php
public function attachments()
{
    return [
        Attachment::fromData(fn () => $this->csv, 'export.csv')
                ->withMime('text/csv'),
    ];
}
```

### Suggestions

Change the MailPayload class to handle raw data,

**Comment by luanfreitasdev** [comment]
Hello!. It's a little late here. This is currently not supported, but it may soon work. Or feel free to send a Pull Request

Thank you
