### ISSUE TITLE
There are no commands defined in the "ds" namespace

### ISSUE THREAD

**Issue by rezapnu** [laradumps/laradumps#119]
hi
I installed laradumps by composer on my laravel project and installed windows app on my system. then i ran  "php artisan ds:init" but this message back to me:
                                    ERROR  There are no commands defined in the "ds" namespace.
how can I fix that? please guide me.
thanks.

**Comment by luanfreitasdev** [comment]
Hello! Some things changed in version 2. Please see the upgrade guide

https://laradumps.dev/get-started/upgrade-guide.html

**Comment by rezapnu** [comment]
Hello there
Thanks for your email. I followed steps in version 2 but I installed
windows desktop v1.7.2 and that don't show any debug in its window. If I
have to installation the new version,please let me know. By the way, this
link for the new version returns back error 404.
https://github.com/laradumps/app/releases/download/v2.1.0/LaraDumps-Setup-2.1.1.exe
thanks.
