### ISSUE TITLE
Falha no configure

### ISSUE THREAD

**Issue by Jeferson-N** [laradumps/laradumps#121]
Bom dia!

Estou utilizando o sail em um ambiente WSL2, porém não funcionou com a configuração abaixo.

![image](https://github.com/laradumps/laradumps/assets/18485370/e0d71a75-f0bc-49c9-9207-bfbe27c56add)

![image](https://github.com/laradumps/laradumps/assets/18485370/5b6859e4-0556-4ba0-a259-cc6cacf2086b)

Existe alguma outra configuração ?

_Originally posted by @Jeferson-N in https://github.com/laradumps/laradumps/issues/116#issuecomment-1684944245_

**Comment by isckosta** [comment]
O meu também está assim. Quando clico e Salvar após a configuração não acontece nada.

**Comment by brunxav** [comment]
O meu também está assim.

**Comment by alansgonzaga** [comment]
![image](https://github.com/laradumps/laradumps/assets/26310779/254431a8-a04f-49f3-95ec-46d831051828)
Estava funcionando até ontem. E hoje não consigo mais rodar nenhum ds() no laradumps, parece que ele não encontra o aplicativo

Nenhum dump ds() aparece.

**Comment by ana-lisboa** [comment]
espreita este comentario, ao usar o ip do wsl resolvi o problema https://github.com/laradumps/laradumps/issues/86#issuecomment-1430381820

**Comment by luanfreitasdev** [comment]
Hello everyone! 

(_In English to make it readable for everyone_)

I understand this is a problem with the '**configure**' command which cannot handle all cases or is not very clear in the console output. Therefore, this command is deprecated and will be released starting with version 3.0 of laradumps and version 2.0 of laradumps-core.

The new command will replace it with "**vendor/bin/laradumps init**". This will adjust the initial environment (host) in the env, and the project will be automatically added to the app without configuring it **(today, we have a registration screen, and I wouldn't say I like the complexity).**

The launch is approaching. Thanks!
