### ISSUE TITLE
[BUG] dsd(123) renders an array like dump on app

### ISSUE THREAD

**Issue by eness** [laradumps/laradumps#123]
#### Have you searched through other issues to see if your problem is already reported or has been fixed?

- [x] Yes - I did not find it.
- [ ] No

#### Did you read the [documentation](https://laradumps.dev/)?

- [x] Yes - I did not find it.
- [ ] No

#### Have you tried to reconfigure LaraDumps?

To configure LaraDumps, run: `php artisan ds:init`.

- [x] Yes - I didn't work.
- [ ] No, I believe this error is not related the configuration.

### Software Version

You can run `composer show -i` and `npm list` to list installed package with their versions.

| Software  | Version (exactly) |
|-----------|-------------------|
| LaraDumps App |   2.3.3                |
| LaraDumps package   |     2.2.0              |
| Laravel  |                   |  10.28
| Operating System  |  WSL2 & php-fpm docker                 |

#### What is your project Environment?

- [ ] Laravel Valet
- [ ] Laravel Sail
- [ ] Docker
- [ ] XAMPP
- [ ] Laragon
- [x] Other - please specify: Bagisto

---

### What happened?

I've treid to test a dump using `dsd(123)` on Artisan tinker but it printed a dump log as if like an array with a single value "123"

### Steps to Reproduce the problem

php artisan tinker
type `dsd(123)` and enter
see the log output on desktop app

## Extra information

![image](https://github.com/laradumps/laradumps/assets/2032225/26660ca8-c89d-4d40-ad3b-f40a0cddb984)

**Comment by luanfreitasdev** [comment]
Fixed: https://github.com/laradumps/laradumps/pull/125
