### ISSUE TITLE
Suporte ao Livewire

### ISSUE THREAD

**Issue by Henriquex25** [laradumps/laradumps#126]
Gostaria de saber se tem previsão e se faz parte do backlog voltar a debugar o Livewire?

Estou parado na versão 1.7.2 por conta do Livewire que é um fator importante pra mim

**Comment by luanfreitasdev** [comment]
Olá @Henriquex25 ! No momento não há planos para isso por causa da nova ferramenta que Caleb apresentou na Laracon.
