### ISSUE TITLE
[BUG] Trait "LaraDumps\LaraDumpsCore\Concerns\Traceable" not found

### ISSUE THREAD

**Issue by amirudinaniq** [laradumps/laradumps#139]
# 🛻 LaraDumps Bug Report

#### Have you searched through other issues to see if your problem is already reported or has been fixed?

- [x] Yes - I did not find it.
- [ ] No

#### Did you read the [documentation](https://laradumps.dev/)?

- [x] Yes - I did not find it.
- [ ] No

#### Have you tried to reconfigure LaraDumps?

To configure LaraDumps, run: `php artisan ds:init`.

- [x] Yes - I didn't work. I received the same error
- [ ] No, I believe this error is not related the configuration.

### Software Version

You can run `composer show -i` and `npm list` to list installed package with their versions.

| Software  | Version (exactly) |
|-----------|-------------------|
| LaraDumps App |        2.4.3           |
| LaraDumps package   |        v2.3.1           |
| Laravel  |          9.52.16         |
| Operating System  |             MacOS      |

#### What is your project Environment?

- [x] Laravel Valet
- [ ] Laravel Sail
- [ ] Docker
- [ ] XAMPP
- [ ] Laragon
- [ ] Other - please specify: ________

---

### What happened?

I received "Trait "LaraDumps\LaraDumpsCore\Concerns\Traceable" not found" when trying to install LaraDumps. How to fix this?

## Extra information

**Screenshots**

<img width="1357" alt="Screenshot 2024-02-29 at 5 15 25 PM" src="https://github.com/laradumps/laradumps/assets/72658354/a5919d19-c784-4b4d-8eed-caa047af365e">

**Comment by luanfreitasdev** [comment]
Hello!, can you install the latest version?

`composer require laradumps/laradumps ^2.5 --dev -W`

**Comment by amirudinaniq** [comment]
I can't, I get this error. 

<img width="1406" alt="Screenshot 2024-03-01 at 9 23 09 AM" src="https://github.com/laradumps/laradumps/assets/72658354/dfd66f2c-93d2-44c6-b094-76fa1edf4798">

**Comment by kiddtang** [comment]
seems like Laravel v9 
can only install "laradumps/laradumps": "2.2.1", without errors.

**Comment by luanfreitasdev** [comment]
Hello!. Can you remove and install it again?

`composer remove laradumps/laradumps`

`composer require laradumps/laradumps --dev -W`

**Comment by kiddtang** [comment]
> Hello!. Can you remove and install it again?
> 
> `composer remove laradumps/laradumps`
> 
> `composer require laradumps/laradumps --dev -W`

Tried. It is still the exact same error.

You can't reproduce on Laravel Framework `v9.52.16` ?

**Comment by luanfreitasdev** [comment]
Fixed: https://github.com/laradumps/laradumps/releases/tag/v2.5.1
