### ISSUE TITLE
v3 - Pest tests

### ISSUE THREAD

**Issue by Krato** [laradumps/laradumps#144]
#### Have you searched through other issues to see if your problem is already reported or has been fixed?

- [X ] Yes - I did not find it.
- [ ] No

#### Did you read the [documentation](https://laradumps.dev/)?

- [ X] Yes - I did not find it.
- [ ] No

#### Have you tried to reconfigure LaraDumps?

To configure LaraDumps, run: `php artisan ds:init`.

- [X ] Yes - I didn't work.
- [ ] No, I believe this error is not related the configuration.

### Software Version

You can run `composer show -i` and `npm list` to list installed package with their versions.

| Software  | Version (exactly) |
|-----------|-------------------|
| LaraDumps App | v3.0.2 |
| LaraDumps | v3.0.0 |
| LaraDumps  core| v2.0.0 |
| Laravel  |10.48.4 |
| Operating System  |Sonoma 14.4.1|

#### What is your project Environment?

- [ ] Laravel Valet
- [ ] Laravel Sail
- [ ] Docker
- [ ] XAMPP
- [ ] Laragon
- [X ] Other - please specify: HERD

---

### What happened?

After installing v3 is impossible to debug PEST tests even with `dd` or `dump`. Also with `ds`.

### Steps to Reproduce the problem

Create a test. For example:

```php
it('test is not dumping', function () {
    dump('test');
    ds('test');
    dd('no output');
})->only();
```

Fire the test:  `./vendor/bin/pest`.

You will see how the test goes out but without output. Just finishes the test. 

Remove the package: `composer remove laradumps/laradumps --dev ^3.0 -W`. Remove the `ds` call from test and run again. 

```php
it('test is not dumping', function () {
    dump('test');
    dd('no output');
})->only();
```

Fire the test:  `./vendor/bin/pest` and you will see your dumps on terminal.

Downgrading to v2 fixed the problem

**Comment by luanfreitasdev** [comment]
Hello!. It's not an issue. Currently, for you to be able to debug within the test, you need to activate `"enabled in testing"`. This still needs to be documented.

By the way, when you use "`dump`", to keep the output in the console you must keep "`original dump`" `true`,

![image](https://github.com/laradumps/laradumps/assets/33601626/232ce265-dc08-452e-8cda-29894c8aacd1)

![image](https://github.com/laradumps/laradumps/assets/33601626/9cbd427b-f2b1-4eaf-8bb5-0ded8e57c50e)

**Comment by Krato** [comment]
Oh, That's good to know :)

But even if we have it disabled, `dump` and `dd` should work right? And that's not happening.

**Comment by luanfreitasdev** [comment]
Right. Understand the problem. I will send a pull request to fix this

**Comment by Krato** [comment]
> Right. Understand the problem. I will send a pull request to fix this

Thank you 😄
