### ISSUE TITLE
[BUG] Upgrade V3 huge slowdown in tests execution

### ISSUE THREAD

**Issue by adrien-delhom** [laradumps/laradumps#147]
#### Have you searched through other issues to see if your problem is already reported or has been fixed?

- [x] Yes - I did not find it.
- [ ] No

#### Did you read the [documentation](https://laradumps.dev/)?

- [x] Yes - I did not find it.
- [ ] No

#### Have you tried to reconfigure LaraDumps?

To configure LaraDumps, run: `php artisan ds:init`.

- [ ] Yes - I didn't work.
- [x] No, I believe this error is not related the configuration.

### Software Version

You can run `composer show -i` and `npm list` to list installed package with their versions.

| Software  | Version (exactly) |
|-----------|-------------------|
| LaraDumps App | 3.0.2                  |
| LaraDumps package   | v3.0.0                   |
| Laravel  | v10.48.4                   |
| Operating System  |  Macbook Pro M1 Sonoma 14.3                |

#### What is your project Environment?

- [ ] Laravel Valet
- [ ] Laravel Sail
- [ ] Docker
- [ ] XAMPP
- [ ] Laragon
- [x] Other - please specify:
Github Action CI: debian:11 (php-8.2-fpm)
Local: php:8.2-fpm-alpine 

---

### What happened?
We've decided to use Laradump rather than Laravel Ray at work, and we're very happy with it. A little problem: I upgraded the package (dev) to V3 on our API, no problem locally, but our CI (tests) went from 10mn to 35mn. I tried to identify the source, but nothing could be done. I also noticed this latency in local, I've had to downgrade it for now.

### Steps to Reproduce the problem
- Prepare some huge tests
- Run your tests (observe time)
- Upgrade to V3
- Run your tests (observe time)

### Suggestions
- Not sure, I have the impression that the ones most affected are feature tests with http requests.

EDIT: Not really good long term solution, but for the moment we remove the package in our CI

## Extra information
Sorry, it's private information, I can't give more detail...

**Screenshots**
After the upgrade
![image](https://github.com/laradumps/laradumps/assets/106613033/c3c5c242-437a-4352-8b0f-d8a9d8619a85)

After the revert
![image](https://github.com/laradumps/laradumps/assets/106613033/b2fe0be9-55f2-4f28-822b-cc14a36dc0a0)

**Comment by luanfreitasdev** [comment]
Hello!

Thank you for reporting this issue

I'm investigating the cause of this. Can you install this version and test it on your CI? It would be great

```bash
composer require laradumps/laradumps --dev dev-147-bug-upgrade-v3-huge-slowdown-in-tests-execution
```

**Comment by adrien-delhom** [comment]
@luanfreitasdev we appreciate your responsiveness!! 

**Our normal CI time with my "tricks" (remove laradumps in CI)**
![image](https://github.com/laradumps/laradumps/assets/106613033/d4fcf8b1-24cd-47cc-a7dc-bd6b88c871e6)

**CI time with your custom branch (not finished yet, achieve 60% of tests ~)**
![image](https://github.com/laradumps/laradumps/assets/106613033/7a0b61fa-994c-43a7-a720-4649b7337f5a)

I don't know if you want to spend more time on this problem, because in the end few users will be impacted, but I think it raises a small concern that may be more "global" to our case.

Recommendation:
I think your package creates a CPU overload somewhere (maybe via Buses or Listener?), which adds a few ms to each of our tests, so if someone uses the package in production it will have an impact if my theory is right.

For that, I'd recommend several approaches:
- use xhprof + [laravel-xhprof ](https://github.com/laracraft-tech/laravel-xhprof)(UI) to track the CPU usage
- xdebug profiler can help too (with clockwork?)

To reproduce IC conditions:
- no laradumps.yml file (so by default laradumps is disabled?)

**Comment by luanfreitasdev** [comment]
Right. This doesn't make sense because all observers are disabled by default unless there is some ds() in the path.

No dependency could cause this

**Comment by luanfreitasdev** [comment]
Is there any dump() in the files?

**Comment by adrien-delhom** [comment]
Nop, no `dd`, `dump` or anything, we have rule to reject that in production

**Comment by luanfreitasdev** [comment]
Could you at some point test again with the latest commit? I would love to understand this and fix it.

**Comment by adrien-delhom** [comment]
I'll test tomorrow morning ;)

**Comment by luanfreitasdev** [comment]
I tested it on 3 projects with large tests and I didn't have this behavior

**Comment by adrien-delhom** [comment]
Are you talking with your fix or with the release version of the package?
Sorry I don't have a lot of time this morning to make the test with CI and your custom branch
