### ISSUE TITLE
Blade helper 

### ISSUE THREAD

**Issue by iamlasse** [laradumps/laradumps#152]
# 🛻 LaraDumps Feature Request

## Summary

A blade helper to replace dd and dump to use Laradumps exclusively for dumping data

### Why is this needed?

Summary pretty much explains it.

### Suggested Solution(s)

A blade helper to replace dd and dump to use Laradumps exclusively for dumping data

### Related issue(s)/PR(s)

Let us know if this is related to any issue/request

**Comment by luanfreitasdev** [comment]
You can use the `@ds` directive. Alternatively, enable 'dump' in your project configuration and use the @dump / @dd directives.

<img width="220" alt="image" src="https://github.com/user-attachments/assets/8954c39f-5a5f-4d6b-8905-fcaeb8e7dda5">
