### ISSUE TITLE
[BUG]Erro ao instalar Laradumps

### ISSUE THREAD

**Issue by nathanraposo** [laradumps/laradumps#164]
# 🛻 LaraDumps Bug Report

<table><tr><td>❗ You <b>MUST</b> use this template to submit an issue or it will be CLOSED. ❗</td></tr></table><br/>

Thank you for reporting a bug and helping us to improve our software!

## Guidelines

`   🐛 `   We use GitHub Issues **EXCLUSIVELY** for tracking bugs and unexpected software behavior.

`   🙏 `  Questions like _"How to...",_ "_how can I..."_, _"I would like to..."_ should be posted in the LaraDumps [Discussions](https://github.com/laradumps/laradumps/discussions) tab.

`   ✍️ `  Give this report a short but meaningful title. Make it easy to spot for others who might be facing the same issue.

`   ⚠️ `  Issues that do not describe a bug will be closed.

#### Have you searched through other issues to see if your problem is already reported or has been fixed?

- [X] Yes - I did not find it.
- [ ] No

#### Did you read the [documentation](https://laradumps.dev/)?

- [X] Yes - I did not find it.
- [ ] No

#### Have you tried to reconfigure LaraDumps?

To configure LaraDumps, run: `php artisan ds:init`.

- [X] Yes - I didn't work.
- [ ] No, I believe this error is not related the configuration.

### Software Version

You can run `composer show -i` and `npm list` to list installed package with their versions.

| Software  | Version (exactly) |
|-----------|-------------------|
| LaraDumps App |  v3.4.0                 |
| LaraDumps package   |  3.2.0                   |
| Laravel  |  11.25.0                  |
| Operating System  |  Ubuntu 22.04.4 LTS                |

#### What is your project Environment?

- [ ] Laravel Valet
- [ ] Laravel Sail
- [X] Docker
- [ ] XAMPP
- [ ] Laragon
- [ ] Other - please specify: ________

---

### What happened?

Estou tentando instalar o Laradumps rodei o comando do composer para instalar conforme está na doc e roda perfeitamente, o problema está em rodar esse comando php artisan ds:init $(pwd) O erro é  ERROR  There are no commands defined in the "ds" namespace. 

### Steps to Reproduce the problem

Tentar rodar o comando php artisan ds:init $(pwd)

### Suggestions

(Do you have any idea how we can fix it?) Não

## Extra information

**Screenshots**
![image](https://github.com/user-attachments/assets/8abbfbd9-bdb7-4e44-8534-ae18e0dc7754)
![image](https://github.com/user-attachments/assets/9c887a60-8916-44ea-9276-c4a9fa406117)
![image](https://github.com/user-attachments/assets/eeb31ee8-d886-4ad3-aa4c-14bab3b5ddd8)

**Comment by nathanraposo** [comment]
Olá voltando aqui e informando que encontramos o motivo de não rodar o comando ds:init

Motivo:
O laradumps estava listado dentro do dont-discover print abaixo, eu removi e funcionou.
![image](https://github.com/user-attachments/assets/5ff48282-b9b9-440b-b22a-bbb843636ab7)

**Comment by luanfreitasdev** [comment]
Ola @nathanraposo ! Que bom que deu certo 

Vou fechar a issue. Obrigado!
