### ISSUE TITLE
Log thrown Exceptions

### ISSUE THREAD

**Issue by marijnbent** [laradumps/laradumps#167]
# 🛻 LaraDumps Feature Request
## Summary
Implement logging for thrown Exceptions in LaraDumps.

### Why is this needed?
Currently, thrown Exceptions are not logged, making it difficult to track and debug issues in the application.

### Suggested Solution(s)
Add a mechanism to capture and log all thrown Exceptions, including relevant context such as timestamp, file, line number, and stack trace.

### Related issue(s)/PR(s)
None at this time.

**Comment by luanfreitasdev** [comment]
Added https://github.com/laradumps/app/pull/347

**Comment by marijnbent** [comment]
thanks @luanfreitasdev !
