### ISSUE TITLE
[BUG] dd function not working

### ISSUE THREAD

**Issue by guiwestrup** [laradumps/laradumps#170]
### What happened?

simply try to run the dd('a') and return 500:
Not generate log in nginx or php-fpm

![image](https://github.com/user-attachments/assets/f57e85bb-c90f-44b2-9d80-8c7a8036b401)
![image](https://github.com/user-attachments/assets/0225c78d-57e8-4e4f-a111-d2efb4ddc759)
![image](https://github.com/user-attachments/assets/754a1f44-3693-48c4-be53-104c63211d1b)

#### Have you searched through other issues to see if your problem is already reported or has been fixed?

- [X] Yes - I did not find it.
- [ ] No

#### Did you read the [documentation](https://laradumps.dev/)?

- [X] Yes - I did not find it.
- [ ] No

#### Have you tried to reconfigure LaraDumps?

To configure LaraDumps, run: `php artisan ds:init`.

- [X] Yes - I didn't work.
- [ ] No, I believe this error is not related the configuration.

### Software Version

You can run `composer show -i` and `npm list` to list installed package with their versions.

├── @ably/laravel-echo@1.0.6
├── @alpinejs/mask@3.14.3
├── @ryangjchandler/alpine-tooltip@2.0.1
├── @tailwindcss/forms@0.5.9
├── ably@1.2.50
├── autoprefixer@10.4.20
├── axios@1.7.7
├── laravel-echo@1.16.1
├── laravel-vite-plugin@1.0.5
├── postcss@8.4.47
├── pusher-js@8.4.0-rc2
├── sweetalert2@11.14.4
├── tailwindcss@3.4.13
└── vite@5.4.8

| Software  | Version (exactly) |
|-----------|-------------------|
ably/ably-php                      1.1.10  Ably REST client library for PHP.
ably/laravel-broadcaster           1.0.6   An Ably broadcaster for Laravel
barryvdh/laravel-debugbar          3.14.6  PHP Debugbar integration for Laravel
barryvdh/laravel-ide-helper        3.2.2   Laravel IDE Helper, generates correct PHPDoc...
barryvdh/reflection-docblock       2.1.3  
brick/math                         0.12.1  Arbitrary-precision arithmetic library
carbonphp/carbon-doctrine-types    3.2.0   Types to use Carbon in Doctrine
clue/redis-protocol                0.3.2   A streaming Redis protocol (RESP) parser and...
clue/redis-react                   2.7.0   Async Redis client implementation, built on ...
composer/class-map-generator       1.4.0   Utilities to scan PHP code and generate clas...
composer/pcre                      3.3.1   PCRE wrapping library that offers type-safe ...
composer/semver                    3.4.3   Semver library that offers utilities, versio...
dflydev/dot-access-data            3.0.3   Given a deep data structure, access data by ...
doctrine/deprecations              1.1.3   A small layer on top of trigger_error(E_USER...
doctrine/inflector                 2.0.10  PHP Doctrine Inflector is a small library th...
doctrine/lexer                     3.0.1   PHP Doctrine Lexer parser library that can b...
dragonmantank/cron-expression      3.4.0   CRON for PHP: Calculate the next or previous...
egulias/email-validator            4.0.2   A library for validating emails against seve...
evenement/evenement                3.0.2   Événement is a very simple event dispatchi...
ezyang/htmlpurifier                4.18.0  Standards compliant HTML filter written in PHP
fakerphp/faker                     1.23.1  Faker is a PHP library that generates fake d...
filp/whoops                        2.16.0  php error handling for cool kids
fruitcake/php-cors                 1.3.0   Cross-origin resource sharing library for th...
graham-campbell/result-type        1.1.3   An Implementation Of The Result Type
guzzlehttp/guzzle                  7.9.2   Guzzle is a PHP HTTP client library
guzzlehttp/promises                2.0.4   Guzzle promises library
guzzlehttp/psr7                    2.7.0   PSR-7 message implementation that also provi...
guzzlehttp/uri-template            1.0.3   A polyfill class for uri_template of PHP
hamcrest/hamcrest-php              2.0.1   This is the PHP port of Hamcrest Matchers
laradumps/laradumps                3.2.0   A Dump Component for Laravel.
laradumps/laradumps-core           2.3.1   LaraDumps is a friendly app designed to boos...
laravel/breeze                     2.2.4   Minimal Laravel authentication scaffolding w...
laravel/framework                  11.30.0 The Laravel Framework.
laravel/pail                       1.2.0   Easily delve into your Laravel application's...
laravel/pint                       1.18.1  An opinionated code formatter for PHP.
laravel/prompts                    0.3.1   Add beautiful and user-friendly forms to you...
laravel/reverb                     1.4.2   Laravel Reverb provides a real-time WebSocke...
laravel/sail                       1.37.1  Docker files for running a basic Laravel app...
laravel/serializable-closure       1.3.5   Laravel Serializable Closure provides an eas...
laravel/tinker                     2.10.0  Powerful REPL for the Laravel framework.
league/commonmark                  2.5.3   Highly-extensible PHP Markdown parser which ...
league/config                      1.2.0   Define configuration arrays with strict sche...
league/flysystem                   3.29.1  File storage abstraction for PHP
league/flysystem-local             3.29.0  Local filesystem adapter for Flysystem.
league/mime-type-detection         1.16.0  Mime-type detection for Flysystem
livewire/livewire                  3.5.12  A front-end framework for Laravel.
livewire/volt                      1.6.5   An elegantly crafted functional API for Lara...
maatwebsite/excel                  3.1.58  Supercharged Excel exports and imports in La...
maennchen/zipstream-php            3.1.1   ZipStream is a library for dynamically strea...
markbaker/complex                  3.0.2   PHP Class for working with complex numbers
markbaker/matrix                   3.0.1   PHP Class for working with matrices
maximebf/debugbar                  1.23.3  Debug bar in the browser for php application
mockery/mockery                    1.6.12  Mockery is a simple yet flexible PHP mock ob...
monolog/monolog                    3.7.0   Sends your logs to files, sockets, inboxes, ...
myclabs/deep-copy                  1.12.0  Create deep copies (clones) of your objects
nesbot/carbon                      3.8.2   An API extension for DateTime that supports ...
nette/schema                       1.3.2   📐 Nette Schema: validating data structure...
nette/utils                        4.0.5   🛠  Nette Utils: lightweight utilities for...
nikic/php-parser                   5.3.1   A PHP parser written in PHP
nunomaduro/collision               8.5.0   Cli error handling for console/command-line ...
nunomaduro/termwind                2.2.0   Its like Tailwind CSS, but for the console.
paragonie/sodium_compat            2.1.0   Pure PHP implementation of libsodium; uses t...
phar-io/manifest                   2.0.4   Component for reading phar.io manifest infor...
phar-io/version                    3.2.1   Library for handling version information and...
phpdocumentor/reflection-common    2.2.0   Common reflection classes used by phpdocumen...
phpdocumentor/type-resolver        1.9.0   A PSR-5 based resolver of Class names, Types...
phpoffice/phpspreadsheet           1.29.2  PHPSpreadsheet - Read, Create and Write Spre...
phpoption/phpoption                1.9.3   Option Type for PHP
phpstan/phpdoc-parser              1.33.0  PHPDoc parser with support for nullable, int...
phpunit/php-code-coverage          11.0.7  Library that provides collection, processing...
phpunit/php-file-iterator          5.1.0   FilterIterator implementation that filters f...
phpunit/php-invoker                5.0.1   Invoke callables with a timeout
phpunit/php-text-template          4.0.1   Simple template engine.
phpunit/php-timer                  7.0.1   Utility class for timing
phpunit/phpunit                    11.4.3  The PHP Unit Testing framework.
predis/predis                      2.2.2   A flexible and feature-complete Redis client...
psr/clock                          1.0.0   Common interface for reading the clock.
psr/container                      2.0.2   Common Container Interface (PHP FIG PSR-11)
psr/event-dispatcher               1.0.0   Standard interfaces for event handling.
psr/http-client                    1.0.3   Common interface for HTTP clients
psr/http-factory                   1.1.0   PSR-17: Common interfaces for PSR-7 HTTP mes...
psr/http-message                   2.0     Common interface for HTTP messages
psr/log                            3.0.2   Common interface for logging libraries
psr/simple-cache                   3.0.0   Common interfaces for simple caching
psy/psysh                          0.12.4  An interactive shell for modern PHP.
pusher/pusher-php-server           7.2.6   Library for interacting with the Pusher REST...
ralouphie/getallheaders            3.0.3   A polyfill for getallheaders.
ramsey/collection                  2.0.0   A PHP library for representing and manipulat...
ramsey/uuid                        4.7.6   A PHP library for generating and working wit...
ratchet/rfc6455                    0.3.1   RFC6455 WebSocket protocol handler
react/cache                        1.2.0   Async, Promise-based cache interface for Rea...
react/dns                          1.13.0  Async DNS resolver for ReactPHP
react/event-loop                   1.5.0   ReactPHP's core reactor event loop that libr...
react/promise                      3.2.0   A lightweight implementation of CommonJS Pro...
react/promise-timer                1.11.0  A trivial implementation of timeouts for Pro...
react/socket                       1.16.0  Async, streaming plaintext TCP/IP and secure...
react/stream                       1.4.0   Event-driven readable and writable streams f...
rybakit/msgpack                    0.9.1   A pure PHP implementation of the MessagePack...
sebastian/cli-parser               3.0.2   Library for parsing CLI options
sebastian/code-unit                3.0.1   Collection of value objects that represent t...
sebastian/code-unit-reverse-lookup 4.0.1   Looks up which function or method a line of ...
sebastian/comparator               6.2.1   Provides the functionality to compare PHP va...
sebastian/complexity               4.0.1   Library for calculating the complexity of PH...
sebastian/diff                     6.0.2   Diff implementation
sebastian/environment              7.2.0   Provides functionality to handle HHVM/PHP en...
sebastian/exporter                 6.1.3   Provides the functionality to export PHP var...
sebastian/global-state             7.0.2   Snapshotting of global state
sebastian/lines-of-code            3.0.1   Library for counting the lines of code in PH...
sebastian/object-enumerator        6.0.1   Traverses array structures and object graphs...
sebastian/object-reflector         4.0.1   Allows reflection of object attributes, incl...
sebastian/recursion-context        6.0.2   Provides functionality to recursively proces...
sebastian/type                     5.1.0   Collection of value objects that represent t...
sebastian/version                  5.0.2   Library that helps with managing the version...
spatie/backtrace                   1.6.2   A better backtrace
symfony/clock                      7.1.6   Decouples applications from the system clock
symfony/console                    7.1.7   Eases the creation of beautiful and testable...
symfony/css-selector               7.1.6   Converts CSS selectors to XPath expressions
symfony/deprecation-contracts      3.5.0   A generic function and convention to trigger...
symfony/error-handler              7.1.7   Provides tools to manage errors and ease deb...
symfony/event-dispatcher           7.1.6   Provides tools that allow your application c...
symfony/event-dispatcher-contracts 3.5.0   Generic abstractions related to dispatching ...
symfony/finder                     7.1.6   Finds files and directories via an intuitive...
symfony/http-foundation            7.1.7   Defines an object-oriented layer for the HTT...
symfony/http-kernel                7.1.7   Provides a structured process for converting...
symfony/mailer                     7.1.6   Helps sending emails
symfony/mime                       7.1.6   Allows manipulating MIME messages
symfony/polyfill-ctype             1.31.0  Symfony polyfill for ctype functions
symfony/polyfill-intl-grapheme     1.31.0  Symfony polyfill for intl's grapheme_* funct...
symfony/polyfill-intl-idn          1.31.0  Symfony polyfill for intl's idn_to_ascii and...
symfony/polyfill-intl-normalizer   1.31.0  Symfony polyfill for intl's Normalizer class...
symfony/polyfill-mbstring          1.31.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php80             1.31.0  Symfony polyfill backporting some PHP 8.0+ f...
symfony/polyfill-php83             1.31.0  Symfony polyfill backporting some PHP 8.3+ f...
symfony/polyfill-uuid              1.31.0  Symfony polyfill for uuid functions
symfony/process                    7.1.7   Executes commands in sub-processes
symfony/routing                    7.1.6   Maps an HTTP request to a set of configurati...
symfony/service-contracts          3.5.0   Generic abstractions related to writing serv...
symfony/string                     7.1.6   Provides an object-oriented API to strings a...
symfony/translation                7.1.6   Provides tools to internationalize your appl...
symfony/translation-contracts      3.5.0   Generic abstractions related to translation
symfony/uid                        7.1.6   Provides an object-oriented API to generate ...
symfony/var-dumper                 7.1.7   Provides mechanisms for walking through any ...
symfony/yaml                       7.1.6   Loads and dumps YAML files
theseer/tokenizer                  1.2.3   A small library for converting tokenized PHP...
tijsverkoyen/css-to-inline-styles  2.2.7   CssToInlineStyles is a class that enables yo...
vlucas/phpdotenv                   5.6.1   Loads environment variables from `.env` to `...
voku/portable-ascii                2.0.1   Portable ASCII library - performance optimiz...
webmozart/assert                   1.11.0  Assertions to validate method input/output w...

#### What is your project Environment?

- [X] Laravel Valet
- [ ] Laravel Sail
- [ ] Docker
- [ ] XAMPP
- [ ] Laragon
- [ ] Other - please specify: ________

---

**Comment by luanfreitasdev** [comment]
Hello!, did you enable "dump" in the laradumps app?

![image](https://github.com/user-attachments/assets/08ccf711-0a77-4f86-a578-5e81bf80e9c4)

**Comment by guiwestrup** [comment]
![image](https://github.com/user-attachments/assets/5ac76d3a-a7f8-4318-a3c6-d7df14941463)

**Comment by guiwestrup** [comment]
Now that you said it, I read "original dump", that solved the problem.

But I looked in the documentation and couldn't find it.

**Comment by ao-jhelmich** [comment]
I don’t think this should cause a 500 error.

If LaraDumps is disabled (including the dump toggle), dd() should just fall back to Laravel’s default behavior. Disabling the app shouldn’t completely break the native dump functionality.

At the very least, this should either gracefully fall back to the original dump or show a clear message explaining what’s happening. Right now it’s quite confusing, especially since it’s not clearly documented.
