### ISSUE TITLE
Says cannot be opened because the developer cannot be verified

### ISSUE THREAD

**Issue by AshishDhamalaAD** [laradumps/laradumps#23]
<img width="810" alt="image" src="https://user-images.githubusercontent.com/65481305/178907208-8f8dcfe6-e821-4af3-917d-84bc0f65aefb.png">

When I tried to install it on my M1 macbook air, it says this.
However I can open it by going inside the Application folder and right clicking and clicking on open.
Hope this will be fixed soon. It's a great tool. Thanks for making it.

**Comment by dansysanalyst** [comment]
Hi @AshishDhamalaAD,

Please check the steps on the doc for MacOS installation, you can just enable it to open.

https://laradumps.dev/#/laravel/get-started/installation

```
- Open System Preferences.

- Go to the Security & Privacy tab.

- Click on the lock and enter your password, so you can make changes.

- Click “Open Anyway” for LaraDumps.
```

I am using MacOS Intel and it works fine, I believe it would be the same with M1.

This happens because the LaraDumps app is not code signed by Apple. To sign the code, a developer must pay Apple about $100/year. Since this is a free tool, I believe signing the code is not on the plans for a while.

**Comment by AshishDhamalaAD** [comment]
Thanks for the reply.
In M1 there is no option to "Click Open Anyway" but I am able to open it. I is really an awesome app.

What I did is:

1. Click on the  (Apple logo) on the top menu
2. Go to System Preferences.
3. Open the Security & Privacy tab.
4. Click on the 🔒 (lock pad) and enter your password to authenticate.
5. Click on the General tab
6. Select on App store and identified developers 
<img width="546" alt="image" src="https://user-images.githubusercontent.com/65481305/178952604-05b5833b-1a7f-44f3-9849-28c89fa1b6d4.png">

7. After that open Finder
8. You can see **Application** on the left side. Click on it.
<img width="177" alt="image" src="https://user-images.githubusercontent.com/65481305/178952878-96065476-0179-4314-a5b3-c24d73f35e0a.png">

9. Find **LaraDumps.app** and `control` + `click` it.
10. It will show menu. Click on open. 
<img width="525" alt="image" src="https://user-images.githubusercontent.com/65481305/178953549-fef6d245-cdab-48e5-a69d-b691f7ef569a.png">

11. Then allow it and walla it works.

I hope this will be helpful for others.

**Comment by dansysanalyst** [comment]
Just for reference, here is a screenshot of newer versions of macOS:

![authorize](https://user-images.githubusercontent.com/79267265/213947873-534a5797-8b38-4e0c-a79a-636c30d0fbf2.png)
