### ISSUE TITLE
Suporte ao  PHP 7.3

### ISSUE THREAD

**Issue by oliveiraxavier** [laradumps/laradumps#5]
Primeiro quero parabenizá-los pelo projeto, está muito bom, mas muito bom mesmo.
Queria muito usar a ferramenta mas por N motivos preciso usar o PHP 7.3 e a versão atual da ferramenta necessita do PHP 8.
Para usar fiz um fork do repositório [aqui](https://github.com/oliveiraxavier/laradumps/tree/support-php73) e estou usando aqui no meu projeto laravel. Falei com o Tio Jobs via coments do Youtube sobre isso.
Não sei se pretendem manter uma versão com suporte a versões anteriores ao PHP8 mas fica a minha contribuição.
Se desejarem manter uma tag para, por exemplo, faço um pr no repositório do que tenho aqui :)

Segue uma imagem dessa maravilha rodando
![image](https://user-images.githubusercontent.com/7455063/174506402-20916d87-139a-4a80-9171-f1c6dea9d27a.png)

**Comment by vs0uz4** [comment]
@oliveiraxavier,

Levamos alguns pontos em consideração para lançarmos o produto com o suporte ao **PHP** sendo minimamente para a versão _8.x_. Um deles foi a vida útil dos `updates` do **PHP** para versões anteriores a _8.x_, sejam eles de funcionalidades, melhorias ou segurança, que se prestarmos atenção ao gráfico anexado abaixo tiveram sua vida útil vencida para as versões anteriores a _7.3_. A própria versão _7.3_ tendo fim aos seus `updates` agora em novembro de 2022, estando nós já na metade do ano praticamente. Essas questões foram cruciais em nossa decisão, porém consideramos também questões como o suporte a dependências utilizadas no projeto.

![supported_versions](https://user-images.githubusercontent.com/2080547/174660039-274e8c71-54f4-4f59-bbb2-e1426c232b80.jpg)

Devido às questões explicitadas, decidimos não manter suporte a versões inferiores ao PHP 8.0 e por isto não poderemos aceitar `issues` e `pull requests` neste sentido. Gostaríamos de lhe parabenizar pela atitude de contribuir com o open-source, mas esta `issue` deverá ser encerrada.

**Comment by vs0uz4** [comment]
Para aqueles que estiverem a procura de suporte para versões anteriores a _8.x_, estaremos recomendando o seu `repositório/fork`.

**Comment by luanfreitasdev** [comment]
Valeu @oliveiraxavier , pelo fork!

https://github.com/oliveiraxavier/laradumps/tree/support-php73

**Comment by oliveiraxavier** [comment]
Opa, por nada @luanfreitasdev.
