### ISSUE TITLE
Broken Installer for Windows 1.50

### ISSUE THREAD

**Issue by tmbenhura** [laradumps/laradumps#65]
### What happened?

The latest installer for Windows ver 1.50 has an extraction error during the installation. I downloaded it thrice and had the problem repeat itself. The first time was automated from within Laradumps, the other 2 times were manual browser downloads.

### Steps to Reproduce the problem

Download: https://github.com/laradumps/app/releases/download/v1.5.0/LaraDumps-Setup-1.5.0.exe
Install

### Suggestions

Re-build the installer

## Extra information

![laradumps-setup-error](https://user-images.githubusercontent.com/15052407/204543767-e5504b87-52c7-40b8-b964-f73903bdd90a.png)

**Comment by luanfreitasdev** [comment]
Hi, is the problem still happening? This appears to be windows permission

**Comment by tmbenhura** [comment]
> Hi, is the problem still happening? This appears to be windows permission

Not any more thanks. I've installed 1.5.1 with no issues
