### ISSUE TITLE
Error running artisan ds:check on my pipeline

### ISSUE THREAD

**Issue by vicenterusso** [laradumps/laradumps#69]
I can't run `ds:check` on my pipeline because composer doesn't include --dev dependencies.

I get the following error: `There are no commands defined in the "ds" namespace`

Creating another step to include --dev just to check `ds:check`, remove vendor and re-create without --dev is impracticable and a waste of build time.

So, I suggest to include `ds()` to the requirements and ignore the function call if production environment, just like [Ray](https://myray.app/). Also a config flag to allow `ds()` in production would be nice.

**Comment by luanfreitasdev** [comment]
I think that in your case you could install without `--dev` and if you want you can send a PR pointing to v2 that ignores the submission in production

**Comment by vicenterusso** [comment]
Sure! Will do that.
