### ISSUE TITLE
QUeries

### ISSUE THREAD

**Issue by Giovanni-Petrella** [laradumps/laradumps#75]
From 1.6.0  I always have the query display enabled, why? the configuration is right and in the previous version it was fine
![Screenshot_20230116_130051](https://user-images.githubusercontent.com/70906593/212673953-6514a4d4-6dbb-4a07-935e-3948a1d02edd.png)
![Screenshot_20230116_130152](https://user-images.githubusercontent.com/70906593/212673957-d58eade4-332e-4166-9dc1-cf2da05d8841.png)
![Screenshot_20230116_130218](https://user-images.githubusercontent.com/70906593/212673962-09b1d1b5-9335-441d-99bc-7eb7ec0dc1ff.png)

**Comment by luanfreitasdev** [comment]
Hello, can you update your config like this ?

```php
 'send_queries'                       => env('DS_SEND_QUERIES', false),
```

**Comment by Giovanni-Petrella** [comment]
Ok thanks it works, but it's not like there is any consequence when I want to view specific queries

**Comment by luanfreitasdev** [comment]
Hello, can you check how this is in version 2? Thanks
