### ISSUE TITLE
Define project path when using docker

### ISSUE THREAD

**Issue by p08dev** [laradumps/laradumps#76]
# 🛻 LaraDumps Feature Request

## Summary

When clicking a path, it tries to open the file with the docker internal path. It would be nice if we could somehow specify the local project path in, for example, the .env

### Why is this needed?

Cannot open file from the desktop app when using docker.

### Suggested Solution(s)

Adding a configuration option to set a local project path like:
`DS_LOCAL_DIR=/home/user/project`

Or am I missing something?

**Comment by dansysanalyst** [comment]
Hi @p08dev,

Is this what you mean?

https://laradumps.dev/#/laravel/get-started/configuration?id=remote-vscode-wsl2

```shell
DS_PREFERRED_IDE=vscode_remote
DS_PREFERRED_WSL_DISTRO=Ubuntu
DS_REMOTE_PATH=/home/jamesbond/Projects/save-the-queen-app
DS_WORKDIR=/var/www/html
```

**Comment by p08dev** [comment]
Hey @dansysanalyst,

kind of... I am on macOS, running my project in Docker. If I configure it like the documentation describes, it starts vscode but won't open any file:

<img width="1136" alt="Screenshot 2023-02-13 at 10 29 46" src="https://user-images.githubusercontent.com/8152667/218421101-c54b68c7-65df-4d71-91a1-1e5d0dac1338.png">

It only shows "Disconnected from WSL".
Here is my .env:

```
DS_APP_HOST=host.docker.internal
DS_APP_PORT=9191
DS_SEND_QUERIES=true
DS_SEND_HTTP_CLIENT_REQUESTS=true
DS_SEND_JOBS=true
DS_SEND_COMMANDS=true
DS_SEND_LOGS=true
DS_SEND_LIVEWIRE_COMPONENTS=true
DS_LIVEWIRE_EVENTS=true
DS_LIVEWIRE_DISPATCH=true
DS_SEND_LIVEWIRE_FAILED_VALIDATION=true
DS_AUTO_CLEAR_ON_PAGE_RELOAD=false
DS_AUTO_INVOKE_APP=true

DS_PREFERRED_IDE=vscode_remote
DS_PREFERRED_WSL_DISTRO=Ubuntu
DS_REMOTE_PATH=/Users/p8/Projects/test-project
DS_WORKDIR=/var/www/html
```

Am I missing something, or does this only support WSL?

**Comment by dansysanalyst** [comment]
Hi @p08dev,

I have tested this approach with Laravel Sail (Docker) and my host system is macOS, hopefully it will be helpful.

First, create a new editor handler inside `config/laradumps.php`. I called mine `vscode_docker`:

```php
    'ide_handlers' => [
        //other ides...

        'vscode_docker' => [
            'handler'        => 'vscode://file/',
            'line_separator' => ':',
            'remote_path'    => '/Users/dan/projects/my-project', //<============ Path on my machine host
            'work_dir'       => '/var/www/html'  //<============ Path inside Docker
        ],
    ],
```

Then, I configured:

`remote_path` as my macOS path, the folder where my project lives.
`work_dir` as the path inside Docker.

(I know, it doesn't match the key name)

Next, I've updated `.env` to use this new configuration:

```env
DS_APP_HOST=host.docker.internal
DS_APP_PORT=9191
DS_SEND_QUERIES=true
DS_SEND_HTTP_CLIENT_REQUESTS=true
DS_SEND_JOBS=true
DS_SEND_COMMANDS=true
DS_SEND_LOGS=true
DS_SEND_LIVEWIRE_COMPONENTS=true
DS_LIVEWIRE_EVENTS=true
DS_LIVEWIRE_DISPATCH=true
DS_SEND_LIVEWIRE_FAILED_VALIDATION=true
DS_AUTO_CLEAR_ON_PAGE_RELOAD=false
DS_AUTO_INVOKE_APP=false
DS_PREFERRED_IDE=my_vscode #<======
```

Now, you should be getting LaraDumps to open your 

This is not intuitive, and I believe there is room for improvement in V2.

cc: @luanfreitasdev

**Comment by p08dev** [comment]
Thanks, @dansysanalyst! It works! I should have thought of that...
