### ISSUE TITLE
Tests run extremely slowly when Laradumps App is closed and Send Queries is Enabled

### ISSUE THREAD

**Issue by tmbenhura** [laradumps/laradumps#79]
### Software Version

| Software  | Version (exactly) |
|-----------|-------------------|
| LaraDumps App |  v1.5.1  |
| LaraDumps package   | v1.7.0  |
| Laravel  |  v8.83.27   |
| Operating System  |  Win 11  |

#### What is your project Environment?

- [ ] Other - Running tests from command line

---

### What happened?

My tests were taking incredibly long to execute. After a long day of debugging, I realised that because events are dispatched synchronously, the test RefreshDatabase trait migrations were triggering "Illuminate\Database\Events\QueryExecuted" events. These in turn would trigger Laradumps to send the queries (DS_SEND_QUERIES=true) to the Laradumps App.

But, since Laradumps was not running, the SendPayload has to timeout on its curl requests 3 times per migration-related query (CREATE TABLE; INSERT INTO migrations; CREATE INDEX). Each table migration was thus taking 2 seconds to execute, cumulatively 60 seconds per test. 

### Steps to Reproduce the problem

- Enable DS_SEND_QUERIES=true
- Close the Laradumps App
- Run a test using the RefreshDatabase trait

I assume the same problem would occur with DS_SEND_LOGS=true as well.

### Suggestions

Improve the developer experience by providing a warning on repeat curl failures.
- Print out on the console if running a test/command line
- Notice if running on web (requests also take very long if Laradumps App is closed and DS_SEND_QUERIES=true)
- Circuit breaker in production
- Wake up Laradumps App if it is not running (Would be great, but probably not easy to implement)

**Comment by dansysanalyst** [comment]
Hi @tmbenhura,

While this is not a fix, you could add `DS_SEND_QUERIES=false` to your `phpunit.xml` file as follows:

```xml
<?xml version="1.0" encoding="UTF-8"?>

[...]
    <php>
        <env name="APP_ENV" value="testing"/>
        <env name="DS_SEND_QUERIES" value="false"/>
        [...]
    </php>
</phpunit>
```

This change would disable sending queries while running the tests.

Also, @luanfreitasdev and I have been discussing this issue to find the best solution possible.

Thanks

**Comment by tmbenhura** [comment]
Thanks for solution. I forgot to mention that I had to do that, as the
important queries are usually drowned by the migration queries anyway.

**Comment by luanfreitasdev** [comment]
I believe this is the easiest way to solve the problem.

**Comment by Cronay** [comment]
Will this be fixed in the foreseeable future? I just wasted 4-5 hours finding the issue with our tests running slow in a really messy commit history and I assume other people will have similar experiences.

**Comment by luanfreitasdev** [comment]
Hello!. This is documented

https://laradumps.dev/debug/testing-environment.html#configuration-example
