### ISSUE TITLE
Laradumps and WSL2

### ISSUE THREAD

**Issue by K2ouMais** [laradumps/laradumps#86]
Hello guys,

how do you run Laradumps with WSL2?

I am using a testproject on WSL2 and run it through ```php artisan serve``` but anything is beeing dumped in the app.

Am I missing something?

Thanks in advance

**Comment by dansysanalyst** [comment]
Hi @K2ouMais, 
I was sure I replied to this issue, now I can't see my reply (I hope I didn't reply accidentally somewhere else).

Do you have the [host key](https://laradumps.dev/#/laravel/get-started/configuration?id=host) configured as `DS_APP_HOST=host.docker.internal` in your `.env`?

I am on a Mac, so I can't run WSL, but maybe this 📽️ [YouTube video](https://youtu.be/8KsHhQ6GcBg?t=516) by @icarojobs (in Portuguese) can be helpful. It was recorded for another version but it still applies.

💡 There are also some settings for [VSCode in WSL2](https://laradumps.dev/#/laravel/get-started/configuration?id=remote-vscode-wsl2) that can be useful.

Thanks for submitting an issue!

**Comment by K2ouMais** [comment]
That setting is for getting it working with docker. I got it to work with docker without a problem. 👍🏻

What I wanted was to get it to run with WSL2 on windows. For this I would love to make it work with a simple ```php artisan serve```.

I know this is not a simple task if I take a look at Spatie Ray. They have a way to run it, but it is complicated.

**Comment by luanfreitasdev** [comment]
Hi @K2ouMais , did you try to put the ipv4?
```bash
DS_APP_HOST=0.0.0.0
```
or
```bash
DS_APP_HOST=192.168.0....
```
![image](https://user-images.githubusercontent.com/33601626/218337814-0804dd43-0f66-45d5-9380-0659fd097bba.png)

**Comment by K2ouMais** [comment]
Dan and I will tomorrow try to get a way around this.

I think personaly wsl2 has a great potential and needs some attention because not everyone likes to use Docker or Laravel Sail that also uses docker .

**Comment by K2ouMais** [comment]
This is not a issue. Let me explain.

First you have to get the IP of your WSL2 instance:
![ip](https://user-images.githubusercontent.com/52510455/218862722-48c6e6a1-2286-4cc1-b843-13eea1e4421d.png)

And after that you just have to insert that IP into your .env file after a ```php artisan ds:init```.

In my case my .env file vars for Laradumps looks like this:
![env](https://user-images.githubusercontent.com/52510455/218863147-2bede1d8-cbc7-4634-bb93-bb8dcd803956.png)

After everything is set you could make a test route for dumping something into the app.

Watch out, that you have to change the IP of your .env after every reboot, because the IP will change after that.

I am going to see, if I can find a way around this and make a PR just for completion.

Sorry for the trouble and thank you for Laradumps.

**Comment by dansysanalyst** [comment]
Updated doc: https://deploy-preview-16--laradumps.netlify.app/#/laravel/get-started/configuration?id=wsl

**Comment by ana-lisboa** [comment]
I was having troubles with this as well ( and i've seen other issues mentioning this here), @K2ouMais comment on using the ip solved my issues!

**Comment by dansysanalyst** [comment]
V2 doc link: https://laradumps.dev/get-started/configuration.html#wsl

**Comment by ana-lisboa** [comment]
> V2 doc link: https://laradumps.dev/get-started/configuration.html#wsl

ohhh! since i am using sail on wsl, i thought i needed to use the sail configs!
