### ISSUE TITLE
Send Queries to defined screen

### ISSUE THREAD

**Issue by K2ouMais** [laradumps/laradumps#91]
# 🛻 LaraDumps Feature Request

## Summary

It would be really nice to send the queries to a defined sreen.

### Why is this needed?

It would help to organize the output of the queries.

### Suggested Solution(s)

```php
ds()->toScreen('LaraDumps')->queriesOn('Check user query');
```

### Related issue(s)/PR(s)

Queries are always sent to "screen 1".

**Comment by luanfreitasdev** [comment]
Hello @K2ouMais , 

This feature was implemented in version 2 which will be released soon.

Thanks
