### ISSUE TITLE
[BUG] Empty values are not being displayed

### ISSUE THREAD

**Issue by vicenterusso** [laradumps/laradumps#97]
#### Have you searched through other issues to see if your problem is already reported or has been fixed?

- [x] Yes - I did not find it.
- [ ] No

#### Did you read the [documentation](https://laradumps.dev/)?

- [x] Yes - I did not find it.
- [ ] No

#### Have you tried to reconfigure LaraDumps?

To configure LaraDumps, run: `php artisan ds:init`.

- [ ] Yes - I didn't work.
- [x] No, I believe this error is not related the configuration.

#### What is your project Environment?

- [ ] Laravel Valet
- [ ] Laravel Sail
- [x] Docker
- [ ] XAMPP
- [ ] Laragon
- [ ] Other - please specify: ________

---

### What happened?

Null and "empty" values are not displayed on Laradumps

### Steps to Reproduce the problem

```php
ds('');
ds(0);
ds('0');
ds(null)
```

**Comment by dansysanalyst** [comment]
Thanks for reporting this bug @vicenterusso!
